name: MurderMystery
main: plugily.projects.murdermystery.Main
authors: [ PlugilyProjects, Tigerpanzer_02 ]
version: ${project.version}
softdepend: [CorpseReborn, PlaceholderAPI, Parties, Spigot-Party-API-PAF, PartyAndFriends, ViaVersion, ProtocolSupport]
api-version: 1.13

commands:
  MurderMystery:
    description: MurderMystery Commands
    usage: "\u00A76Correct usage: /murdermystery [option]"
    aliases: [mm, murder]
  MurderMysteryAdmin:
    description: MurderMysteryAdmin commands
    usage: "\u00A76Correct usage: /murdermysterya [option]"
    aliases: [mma, murderadmin]

permissions:
  murdermystery.admin.*:
    default: op
    children:
      murdermystery.updatenotify: true
      murdermystery.admin: true
      murdermystery.admin.setup: true
      murdermystery.admin.delete: true
      murdermystery.admin.list: true
      murdermystery.admin.spychat: true
      murdermystery.admin.stopgame: true
      murdermystery.admin.forcestart: true
      murdermystery.admin.addsign: true
      murdermystery.admin.clear: true
      murdermystery.admin.sign.create: true
      murdermystery.admin.sign.break: true
      murdermystery.admin.reload: true
      murdermystery.command.override: true